// Auto-generated by migrate.ts - do not edit
import * as _20260824165522_initial from "./20260824165522_initial.js"

export const migrations = {
  "20260824165522_initial": _20260824165522_initial.default,
} as const
