// Auto-generated by migrate.ts - do not edit
import * as _20260308214649_initial from "./20260308214649_initial.js"

export const migrations = {
  "20260308214649_initial": _20260308214649_initial.default,
} as const
