// Auto-generated by migrate.ts - do not edit
import * as _20260309203411_initial from "./20260309203411_initial.js"

export const migrations = {
  "20260309203411_initial": _20260309203411_initial.default,
} as const
