// GENERATED by @gel/generate v0.7.1
// This file is automatically generated from .edgeql query files.
// To make changes, edit the source .edgeql file and regenerate.

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _extauth from "./ext/auth";
export type $EdiblePart = {
  "FRUTO": $.$expr_Literal<$EdiblePart>;
  "FLOR": $.$expr_Literal<$EdiblePart>;
  "FOLHA": $.$expr_Literal<$EdiblePart>;
  "CAULE": $.$expr_Literal<$EdiblePart>;
  "SEMENTE": $.$expr_Literal<$EdiblePart>;
  "CASCA": $.$expr_Literal<$EdiblePart>;
  "BULBO": $.$expr_Literal<$EdiblePart>;
  "BROTO": $.$expr_Literal<$EdiblePart>;
  "RAIZ": $.$expr_Literal<$EdiblePart>;
  "TUBERCULO": $.$expr_Literal<$EdiblePart>;
  "RIZOMA": $.$expr_Literal<$EdiblePart>;
} & $.EnumType<"default::EdiblePart", ["FRUTO", "FLOR", "FOLHA", "CAULE", "SEMENTE", "CASCA", "BULBO", "BROTO", "RAIZ", "TUBERCULO", "RIZOMA"]>;
const EdiblePart: $EdiblePart = $.makeType<$EdiblePart>(_.spec, "b9e15462-1926-11ef-8726-df5f469b3fc4", _.syntax.literal);

export type $EditSuggestionStatus = {
  "PENDING_REVIEW": $.$expr_Literal<$EditSuggestionStatus>;
  "MERGED": $.$expr_Literal<$EditSuggestionStatus>;
  "REJECTED": $.$expr_Literal<$EditSuggestionStatus>;
} & $.EnumType<"default::EditSuggestionStatus", ["PENDING_REVIEW", "MERGED", "REJECTED"]>;
const EditSuggestionStatus: $EditSuggestionStatus = $.makeType<$EditSuggestionStatus>(_.spec, "b8cb7972-1926-11ef-8a1c-377c25ad2a15", _.syntax.literal);

export type $Gender = {
  "FEMININO": $.$expr_Literal<$Gender>;
  "MASCULINO": $.$expr_Literal<$Gender>;
  "NEUTRO": $.$expr_Literal<$Gender>;
} & $.EnumType<"default::Gender", ["FEMININO", "MASCULINO", "NEUTRO"]>;
const Gender: $Gender = $.makeType<$Gender>(_.spec, "b9e15f02-1926-11ef-a146-e56179344337", _.syntax.literal);

export type $HistoryAction = {
  "INSERT": $.$expr_Literal<$HistoryAction>;
  "UPDATE": $.$expr_Literal<$HistoryAction>;
  "DELETE": $.$expr_Literal<$HistoryAction>;
} & $.EnumType<"default::HistoryAction", ["INSERT", "UPDATE", "DELETE"]>;
const HistoryAction: $HistoryAction = $.makeType<$HistoryAction>(_.spec, "ba9ebd36-1926-11ef-bc04-ef55cfb32a6b", _.syntax.literal);

export type $NotePublishStatus = {
  "PRIVATE": $.$expr_Literal<$NotePublishStatus>;
  "COMMUNITY": $.$expr_Literal<$NotePublishStatus>;
  "PUBLIC": $.$expr_Literal<$NotePublishStatus>;
} & $.EnumType<"default::NotePublishStatus", ["PRIVATE", "COMMUNITY", "PUBLIC"]>;
const NotePublishStatus: $NotePublishStatus = $.makeType<$NotePublishStatus>(_.spec, "3cb89da7-0901-11f0-bca9-874a6256f08e", _.syntax.literal);

export type $NoteType = {
  "EXPERIMENTO": $.$expr_Literal<$NoteType>;
  "ENSINAMENTO": $.$expr_Literal<$NoteType>;
  "DESCOBERTA": $.$expr_Literal<$NoteType>;
  "PERGUNTA": $.$expr_Literal<$NoteType>;
  "INSPIRACAO": $.$expr_Literal<$NoteType>;
} & $.EnumType<"default::NoteType", ["EXPERIMENTO", "ENSINAMENTO", "DESCOBERTA", "PERGUNTA", "INSPIRACAO"]>;
const NoteType: $NoteType = $.makeType<$NoteType>(_.spec, "b95be07a-1926-11ef-90c1-1971813d148b", _.syntax.literal);

export type $PlantingMethod = {
  "BROTO": $.$expr_Literal<$PlantingMethod>;
  "ENXERTO": $.$expr_Literal<$PlantingMethod>;
  "ESTACA": $.$expr_Literal<$PlantingMethod>;
  "RIZOMA": $.$expr_Literal<$PlantingMethod>;
  "SEMENTE": $.$expr_Literal<$PlantingMethod>;
  "TUBERCULO": $.$expr_Literal<$PlantingMethod>;
} & $.EnumType<"default::PlantingMethod", ["BROTO", "ENXERTO", "ESTACA", "RIZOMA", "SEMENTE", "TUBERCULO"]>;
const PlantingMethod: $PlantingMethod = $.makeType<$PlantingMethod>(_.spec, "b9e16c4a-1926-11ef-a0d3-451d0295336c", _.syntax.literal);

export type $ResourceFormat = {
  "BOOK": $.$expr_Literal<$ResourceFormat>;
  "FILM": $.$expr_Literal<$ResourceFormat>;
  "SOCIAL_MEDIA": $.$expr_Literal<$ResourceFormat>;
  "VIDEO": $.$expr_Literal<$ResourceFormat>;
  "ARTICLE": $.$expr_Literal<$ResourceFormat>;
  "PODCAST": $.$expr_Literal<$ResourceFormat>;
  "COURSE": $.$expr_Literal<$ResourceFormat>;
  "ACADEMIC_WORK": $.$expr_Literal<$ResourceFormat>;
  "DATASET": $.$expr_Literal<$ResourceFormat>;
  "ORGANIZATION": $.$expr_Literal<$ResourceFormat>;
  "OTHER": $.$expr_Literal<$ResourceFormat>;
} & $.EnumType<"default::ResourceFormat", ["BOOK", "FILM", "SOCIAL_MEDIA", "VIDEO", "ARTICLE", "PODCAST", "COURSE", "ACADEMIC_WORK", "DATASET", "ORGANIZATION", "OTHER"]>;
const ResourceFormat: $ResourceFormat = $.makeType<$ResourceFormat>(_.spec, "ad43ee2d-0cc9-11f0-9068-0dd3f630b03f", _.syntax.literal);

export type $Role = {
  "ADMIN": $.$expr_Literal<$Role>;
  "USER": $.$expr_Literal<$Role>;
  "MODERATOR": $.$expr_Literal<$Role>;
} & $.EnumType<"default::Role", ["ADMIN", "USER", "MODERATOR"]>;
const Role: $Role = $.makeType<$Role>(_.spec, "b88e9408-1926-11ef-b453-4944ba619163", _.syntax.literal);

export type $SourceType = {
  "GOROROBAS": $.$expr_Literal<$SourceType>;
  "EXTERNAL": $.$expr_Literal<$SourceType>;
} & $.EnumType<"default::SourceType", ["GOROROBAS", "EXTERNAL"]>;
const SourceType: $SourceType = $.makeType<$SourceType>(_.spec, "b95a60ec-1926-11ef-a290-e91317b32d1f", _.syntax.literal);

export type $Stratum = {
  "EMERGENTE": $.$expr_Literal<$Stratum>;
  "ALTO": $.$expr_Literal<$Stratum>;
  "MEDIO": $.$expr_Literal<$Stratum>;
  "BAIXO": $.$expr_Literal<$Stratum>;
  "RASTEIRO": $.$expr_Literal<$Stratum>;
} & $.EnumType<"default::Stratum", ["EMERGENTE", "ALTO", "MEDIO", "BAIXO", "RASTEIRO"]>;
const Stratum: $Stratum = $.makeType<$Stratum>(_.spec, "b9e17686-1926-11ef-83b2-67f7f7af8855", _.syntax.literal);

export type $TipSubject = {
  "PLANTIO": $.$expr_Literal<$TipSubject>;
  "CRESCIMENTO": $.$expr_Literal<$TipSubject>;
  "COLHEITA": $.$expr_Literal<$TipSubject>;
} & $.EnumType<"default::TipSubject", ["PLANTIO", "CRESCIMENTO", "COLHEITA"]>;
const TipSubject: $TipSubject = $.makeType<$TipSubject>(_.spec, "b9992dcc-1926-11ef-ae05-012e2feff398", _.syntax.literal);

export type $VegetableLifeCycle = {
  "SEMESTRAL": $.$expr_Literal<$VegetableLifeCycle>;
  "ANUAL": $.$expr_Literal<$VegetableLifeCycle>;
  "BIENAL": $.$expr_Literal<$VegetableLifeCycle>;
  "PERENE": $.$expr_Literal<$VegetableLifeCycle>;
} & $.EnumType<"default::VegetableLifeCycle", ["SEMESTRAL", "ANUAL", "BIENAL", "PERENE"]>;
const VegetableLifeCycle: $VegetableLifeCycle = $.makeType<$VegetableLifeCycle>(_.spec, "b9e18040-1926-11ef-959f-87c0cbbd55cf", _.syntax.literal);

export type $VegetableUsage = {
  "ALIMENTO_ANIMAL": $.$expr_Literal<$VegetableUsage>;
  "ALIMENTO_HUMANO": $.$expr_Literal<$VegetableUsage>;
  "CONSTRUCAO": $.$expr_Literal<$VegetableUsage>;
  "MATERIA_ORGANICA": $.$expr_Literal<$VegetableUsage>;
  "MEDICINAL": $.$expr_Literal<$VegetableUsage>;
  "COSMETICO": $.$expr_Literal<$VegetableUsage>;
  "ORNAMENTAL": $.$expr_Literal<$VegetableUsage>;
  "RITUALISTICO": $.$expr_Literal<$VegetableUsage>;
  "ECOLOGICO": $.$expr_Literal<$VegetableUsage>;
} & $.EnumType<"default::VegetableUsage", ["ALIMENTO_ANIMAL", "ALIMENTO_HUMANO", "CONSTRUCAO", "MATERIA_ORGANICA", "MEDICINAL", "COSMETICO", "ORNAMENTAL", "RITUALISTICO", "ECOLOGICO"]>;
const VegetableUsage: $VegetableUsage = $.makeType<$VegetableUsage>(_.spec, "b9e18ac2-1926-11ef-9fa3-b5aa80daf8b7", _.syntax.literal);

export type $VegetableWishlistStatus = {
  "QUERO_CULTIVAR": $.$expr_Literal<$VegetableWishlistStatus>;
  "SEM_INTERESSE": $.$expr_Literal<$VegetableWishlistStatus>;
  "JA_CULTIVEI": $.$expr_Literal<$VegetableWishlistStatus>;
  "ESTOU_CULTIVANDO": $.$expr_Literal<$VegetableWishlistStatus>;
} & $.EnumType<"default::VegetableWishlistStatus", ["QUERO_CULTIVAR", "SEM_INTERESSE", "JA_CULTIVEI", "ESTOU_CULTIVANDO"]>;
const VegetableWishlistStatus: $VegetableWishlistStatus = $.makeType<$VegetableWishlistStatus>(_.spec, "b9e19f8a-1926-11ef-a4b0-130b98baccca", _.syntax.literal);

export type $AdminCanDoAnythingλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
}>;
type $AdminCanDoAnything = $.ObjectType<"default::AdminCanDoAnything", $AdminCanDoAnythingλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::BlueskyPost" | "default::EditSuggestion" | "default::Image" | "default::Note" | "default::Resource" | "default::Source" | "default::Tag" | "default::Vegetable" | "default::VegetableFriendship" | "default::VegetableTip" | "default::VegetableVariety">;
const $AdminCanDoAnything = $.makeType<$AdminCanDoAnything>(_.spec, "b89bf814-1926-11ef-94e4-79ecd794aa37", _.syntax.literal);

const AdminCanDoAnything: $.$expr_PathNode<$.TypeSet<$AdminCanDoAnything, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($AdminCanDoAnything, $.Cardinality.Many), null);

export type $AuditableλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "created_at": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, true, true>;
  "updated_at": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "created_by": $.LinkDesc<$UserProfile, $.Cardinality.AtMostOne, {}, false, false,  false, true>;
  "<target[is HistoryLog]": $.LinkDesc<$HistoryLog, $.Cardinality.Many, {}, false, false,  false, false>;
  "<target": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Auditable = $.ObjectType<"default::Auditable", $AuditableλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::BlueskyPost" | "default::EditSuggestion" | "default::Image" | "default::Note" | "default::Resource" | "default::Source" | "default::Vegetable" | "default::VegetableFriendship" | "default::VegetableTip" | "default::VegetableVariety">;
const $Auditable = $.makeType<$Auditable>(_.spec, "b8cb8584-1926-11ef-8a39-894e553745ce", _.syntax.literal);

const Auditable: $.$expr_PathNode<$.TypeSet<$Auditable, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Auditable, $.Cardinality.Many), null);

export type $BlueskyPostλShape = $.typeutil.flatten<$AuditableλShape & $AdminCanDoAnythingλShape & {
  "text": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "content": $.LinkDesc<$PostableToBluesky, $.Cardinality.One, {}, true, false,  false, false>;
}>;
type $BlueskyPost = $.ObjectType<"default::BlueskyPost", $BlueskyPostλShape, null, [
  ...$Auditable['__exclusives__'],
  ...$AdminCanDoAnything['__exclusives__'],
  {content: {__element__: $PostableToBluesky, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "default::BlueskyPost">;
const $BlueskyPost = $.makeType<$BlueskyPost>(_.spec, "0ef1bda7-10e7-11f0-90ae-856053fc0adc", _.syntax.literal);

const BlueskyPost: $.$expr_PathNode<$.TypeSet<$BlueskyPost, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($BlueskyPost, $.Cardinality.Many), null);

export type $UserCanInsertλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
}>;
type $UserCanInsert = $.ObjectType<"default::UserCanInsert", $UserCanInsertλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::EditSuggestion" | "default::Image" | "default::Resource" | "default::Source" | "default::Vegetable" | "default::VegetableFriendship" | "default::VegetableTip" | "default::VegetableVariety">;
const $UserCanInsert = $.makeType<$UserCanInsert>(_.spec, "b8b4d06e-1926-11ef-a6e1-67da2400fc3a", _.syntax.literal);

const UserCanInsert: $.$expr_PathNode<$.TypeSet<$UserCanInsert, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($UserCanInsert, $.Cardinality.Many), null);

export type $PublicReadλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
}>;
type $PublicRead = $.ObjectType<"default::PublicRead", $PublicReadλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::EditSuggestion" | "default::Image" | "default::Resource" | "default::Source" | "default::Tag" | "default::UserProfile" | "default::UserWishlist" | "default::Vegetable" | "default::VegetableFriendship" | "default::VegetableTip" | "default::VegetableVariety" | "default::current_user_profile">;
const $PublicRead = $.makeType<$PublicRead>(_.spec, "b8e681c2-1926-11ef-962f-87aa637b9a72", _.syntax.literal);

const PublicRead: $.$expr_PathNode<$.TypeSet<$PublicRead, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($PublicRead, $.Cardinality.Many), null);

export type $ModeratorCanUpdateλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
}>;
type $ModeratorCanUpdate = $.ObjectType<"default::ModeratorCanUpdate", $ModeratorCanUpdateλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::EditSuggestion" | "default::Vegetable">;
const $ModeratorCanUpdate = $.makeType<$ModeratorCanUpdate>(_.spec, "3bf492e5-19fc-11ef-b289-9554b91d09ae", _.syntax.literal);

const ModeratorCanUpdate: $.$expr_PathNode<$.TypeSet<$ModeratorCanUpdate, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($ModeratorCanUpdate, $.Cardinality.Many), null);

export type $EditSuggestionλShape = $.typeutil.flatten<$AuditableλShape & $AdminCanDoAnythingλShape & $UserCanInsertλShape & $PublicReadλShape & $ModeratorCanUpdateλShape & {
  "diff": $.PropertyDesc<_std.$json, $.Cardinality.One, false, false, false, false>;
  "snapshot": $.PropertyDesc<_std.$json, $.Cardinality.One, false, false, false, false>;
  "status": $.PropertyDesc<$EditSuggestionStatus, $.Cardinality.One, false, false, false, false>;
  "reviewed_by": $.LinkDesc<$UserProfile, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "target_object": $.LinkDesc<$Vegetable, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $EditSuggestion = $.ObjectType<"default::EditSuggestion", $EditSuggestionλShape, null, [
  ...$Auditable['__exclusives__'],
  ...$AdminCanDoAnything['__exclusives__'],
  ...$UserCanInsert['__exclusives__'],
  ...$PublicRead['__exclusives__'],
  ...$ModeratorCanUpdate['__exclusives__'],
], "default::EditSuggestion">;
const $EditSuggestion = $.makeType<$EditSuggestion>(_.spec, "b8cdcb6e-1926-11ef-8c9a-db31cf3cff46", _.syntax.literal);

const EditSuggestion: $.$expr_PathNode<$.TypeSet<$EditSuggestion, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($EditSuggestion, $.Cardinality.Many), null);

export type $HistoryLogλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "performed_by": $.LinkDesc<$UserProfile, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "target": $.LinkDesc<$Auditable, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "action": $.PropertyDesc<$HistoryAction, $.Cardinality.One, false, false, false, false>;
  "old": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "timestamp": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, true, true>;
  "new": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $HistoryLog = $.ObjectType<"default::HistoryLog", $HistoryLogλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::HistoryLog">;
const $HistoryLog = $.makeType<$HistoryLog>(_.spec, "ba9ec8d0-1926-11ef-8739-19023b41fdbe", _.syntax.literal);

const HistoryLog: $.$expr_PathNode<$.TypeSet<$HistoryLog, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($HistoryLog, $.Cardinality.Many), null);

export type $UserCanUpdateλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
}>;
type $UserCanUpdate = $.ObjectType<"default::UserCanUpdate", $UserCanUpdateλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::Image" | "default::Source">;
const $UserCanUpdate = $.makeType<$UserCanUpdate>(_.spec, "c2ddaa96-28d3-11ef-9255-33b14342f74c", _.syntax.literal);

const UserCanUpdate: $.$expr_PathNode<$.TypeSet<$UserCanUpdate, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($UserCanUpdate, $.Cardinality.Many), null);

export type $ImageλShape = $.typeutil.flatten<$PublicReadλShape & $AuditableλShape & $UserCanInsertλShape & $UserCanUpdateλShape & $AdminCanDoAnythingλShape & {
  "crop": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "hotspot": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "label": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "sanity_id": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, true, false>;
  "sources": $.LinkDesc<$Source, $.Cardinality.Many, {
    "@order_index": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne>;
  }, false, false, false, false>;
  "<photo[is UserProfile]": $.LinkDesc<$UserProfile, $.Cardinality.Many, {}, false, false,  false, false>;
  "<photo[is current_user_profile]": $.LinkDesc<$current_user_profile, $.Cardinality.Many, {}, false, false,  false, false>;
  "<thumbnail[is Resource]": $.LinkDesc<$Resource, $.Cardinality.Many, {}, false, false,  false, false>;
  "<photos[is VegetableVariety]": $.LinkDesc<$VegetableVariety, $.Cardinality.Many, {}, false, false,  false, false>;
  "<photos[is Vegetable]": $.LinkDesc<$Vegetable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<photo": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<photos": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<thumbnail": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Image = $.ObjectType<"default::Image", $ImageλShape, null, [
  ...$PublicRead['__exclusives__'],
  ...$Auditable['__exclusives__'],
  ...$UserCanInsert['__exclusives__'],
  ...$UserCanUpdate['__exclusives__'],
  ...$AdminCanDoAnything['__exclusives__'],
  {sanity_id: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "default::Image">;
const $Image = $.makeType<$Image>(_.spec, "b8e79012-1926-11ef-9fd5-e57d3cfee760", _.syntax.literal);

const Image: $.$expr_PathNode<$.TypeSet<$Image, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Image, $.Cardinality.Many), null);

export type $WithHandleλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "handle": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
}>;
type $WithHandle = $.ObjectType<"default::WithHandle", $WithHandleλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {handle: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "default::Note" | "default::Resource" | "default::Tag" | "default::UserProfile" | "default::Vegetable" | "default::VegetableTip" | "default::VegetableVariety" | "default::current_user_profile">;
const $WithHandle = $.makeType<$WithHandle>(_.spec, "b8f5bcf0-1926-11ef-9445-030a7aa8972b", _.syntax.literal);

const WithHandle: $.$expr_PathNode<$.TypeSet<$WithHandle, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($WithHandle, $.Cardinality.Many), null);

export type $PostableToBlueskyλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "has_been_posted_to_bluesky": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, true, false, false>;
  "<content[is BlueskyPost]": $.LinkDesc<$BlueskyPost, $.Cardinality.AtMostOne, {}, true, false,  false, false>;
  "<content": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $PostableToBluesky = $.ObjectType<"default::PostableToBluesky", $PostableToBlueskyλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::Note" | "default::Resource" | "default::Vegetable">;
const $PostableToBluesky = $.makeType<$PostableToBluesky>(_.spec, "0f5049f5-10e7-11f0-8795-4ddaaa88ad63", _.syntax.literal);

const PostableToBluesky: $.$expr_PathNode<$.TypeSet<$PostableToBluesky, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($PostableToBluesky, $.Cardinality.Many), null);

export type $NoteλShape = $.typeutil.flatten<$WithHandleλShape & $AuditableλShape & $AdminCanDoAnythingλShape & $PostableToBlueskyλShape & {
  "public": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "publish_status": $.PropertyDesc<$NotePublishStatus, $.Cardinality.One, false, false, false, true>;
  "related_to_notes": $.LinkDesc<$Note, $.Cardinality.Many, {}, false, false,  false, false>;
  "related_notes": $.LinkDesc<$Note, $.Cardinality.Many, {}, false, true,  false, false>;
  "body": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "content_plain_text": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, true>;
  "published_at": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
  "title": $.PropertyDesc<_std.$json, $.Cardinality.One, false, false, false, false>;
  "types": $.PropertyDesc<$NoteType, $.Cardinality.AtLeastOne, false, false, false, false>;
  "related_to_vegetables": $.LinkDesc<$Vegetable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<related_to_notes[is Note]": $.LinkDesc<$Note, $.Cardinality.Many, {}, false, false,  false, false>;
  "<related_notes[is Note]": $.LinkDesc<$Note, $.Cardinality.Many, {}, false, false,  false, false>;
  "<related_notes[is Vegetable]": $.LinkDesc<$Vegetable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<related_notes": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<related_to_notes": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Note = $.ObjectType<"default::Note", $NoteλShape, null, [
  ...$WithHandle['__exclusives__'],
  ...$Auditable['__exclusives__'],
  ...$AdminCanDoAnything['__exclusives__'],
  ...$PostableToBluesky['__exclusives__'],
], "default::Note">;
const $Note = $.makeType<$Note>(_.spec, "b95bef48-1926-11ef-9b50-23c5aa57b178", _.syntax.literal);

const Note: $.$expr_PathNode<$.TypeSet<$Note, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Note, $.Cardinality.Many), null);

export type $WithTagsλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "tags": $.LinkDesc<$Tag, $.Cardinality.Many, {
    "@order_index": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne>;
  }, false, false, false, false>;
  "<mentions[is Tag]": $.LinkDesc<$Tag, $.Cardinality.Many, {}, false, false,  false, false>;
  "<mentions": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $WithTags = $.ObjectType<"default::WithTags", $WithTagsλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::Resource">;
const $WithTags = $.makeType<$WithTags>(_.spec, "ad4410bf-0cc9-11f0-b068-2765fa32ddfc", _.syntax.literal);

const WithTags: $.$expr_PathNode<$.TypeSet<$WithTags, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($WithTags, $.Cardinality.Many), null);

export type $ResourceλShape = $.typeutil.flatten<$WithHandleλShape & $WithTagsλShape & $PublicReadλShape & $AuditableλShape & $UserCanInsertλShape & $AdminCanDoAnythingλShape & $PostableToBlueskyλShape & {
  "thumbnail": $.LinkDesc<$Image, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "credit_line": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "description": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "format": $.PropertyDesc<$ResourceFormat, $.Cardinality.One, false, false, false, false>;
  "title": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "url": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "related_vegetables": $.LinkDesc<$Vegetable, $.Cardinality.Many, {
    "@order_index": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne>;
  }, false, false, false, false>;
  "<related_resources[is Vegetable]": $.LinkDesc<$Vegetable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<related_resources": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Resource = $.ObjectType<"default::Resource", $ResourceλShape, null, [
  ...$WithHandle['__exclusives__'],
  ...$WithTags['__exclusives__'],
  ...$PublicRead['__exclusives__'],
  ...$Auditable['__exclusives__'],
  ...$UserCanInsert['__exclusives__'],
  ...$AdminCanDoAnything['__exclusives__'],
  ...$PostableToBluesky['__exclusives__'],
  {url: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "default::Resource">;
const $Resource = $.makeType<$Resource>(_.spec, "ad45b536-0cc9-11f0-ba6c-a7e0a6f35b86", _.syntax.literal);

const Resource: $.$expr_PathNode<$.TypeSet<$Resource, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Resource, $.Cardinality.Many), null);

export type $SourceλShape = $.typeutil.flatten<$AuditableλShape & $PublicReadλShape & $UserCanInsertλShape & $AdminCanDoAnythingλShape & $UserCanUpdateλShape & {
  "comments": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "credits": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "origin": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "type": $.PropertyDesc<$SourceType, $.Cardinality.One, false, false, false, false>;
  "users": $.LinkDesc<$UserProfile, $.Cardinality.Many, {}, false, false,  false, false>;
  "<sources[is VegetableTip]": $.LinkDesc<$VegetableTip, $.Cardinality.Many, {}, false, false,  false, false>;
  "<sources[is Vegetable]": $.LinkDesc<$Vegetable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<sources[is Image]": $.LinkDesc<$Image, $.Cardinality.Many, {}, false, false,  false, false>;
  "<sources": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Source = $.ObjectType<"default::Source", $SourceλShape, null, [
  ...$Auditable['__exclusives__'],
  ...$PublicRead['__exclusives__'],
  ...$UserCanInsert['__exclusives__'],
  ...$AdminCanDoAnything['__exclusives__'],
  ...$UserCanUpdate['__exclusives__'],
], "default::Source">;
const $Source = $.makeType<$Source>(_.spec, "b95a6dc6-1926-11ef-8eb5-a974d40be59a", _.syntax.literal);

const Source: $.$expr_PathNode<$.TypeSet<$Source, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Source, $.Cardinality.Many), null);

export type $TagλShape = $.typeutil.flatten<$WithHandleλShape & $PublicReadλShape & $AdminCanDoAnythingλShape & {
  "category": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "description": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "names": $.PropertyDesc<$.ArrayType<_std.$str>, $.Cardinality.One, false, false, false, false>;
  "mentions": $.LinkDesc<$WithTags, $.Cardinality.Many, {}, false, true,  false, false>;
  "<tags[is WithTags]": $.LinkDesc<$WithTags, $.Cardinality.Many, {}, false, false,  false, false>;
  "<tags[is Resource]": $.LinkDesc<$Resource, $.Cardinality.Many, {}, false, false,  false, false>;
  "<tags": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Tag = $.ObjectType<"default::Tag", $TagλShape, null, [
  ...$WithHandle['__exclusives__'],
  ...$PublicRead['__exclusives__'],
  ...$AdminCanDoAnything['__exclusives__'],
], "default::Tag">;
const $Tag = $.makeType<$Tag>(_.spec, "adbef8fe-0cc9-11f0-ae50-33b776551b94", _.syntax.literal);

const Tag: $.$expr_PathNode<$.TypeSet<$Tag, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Tag, $.Cardinality.Many), null);

export type $UserλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "identity": $.LinkDesc<_extauth.$Identity, $.Cardinality.One, {}, true, false,  false, false>;
  "created": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "email": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, true, false, false, false>;
  "updated": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "userRole": $.PropertyDesc<$Role, $.Cardinality.AtMostOne, false, false, false, true>;
  "<user[is UserProfile]": $.LinkDesc<$UserProfile, $.Cardinality.AtMostOne, {}, true, false,  false, false>;
  "<user[is current_user_profile]": $.LinkDesc<$current_user_profile, $.Cardinality.Many, {}, false, false,  false, false>;
  "<user": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $User = $.ObjectType<"default::User", $UserλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {identity: {__element__: _extauth.$Identity, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
  {email: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "default::User" | "default::current_user">;
const $User = $.makeType<$User>(_.spec, "b88e9fd4-1926-11ef-aabf-e9b3525330ed", _.syntax.literal);

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);

export type $UserCanSelectλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
}>;
type $UserCanSelect = $.ObjectType<"default::UserCanSelect", $UserCanSelectλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], never>;
const $UserCanSelect = $.makeType<$UserCanSelect>(_.spec, "3c1137c9-19fc-11ef-89d9-2f0b5323c7e6", _.syntax.literal);

const UserCanSelect: $.$expr_PathNode<$.TypeSet<$UserCanSelect, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($UserCanSelect, $.Cardinality.Many), null);

export type $UserProfileλShape = $.typeutil.flatten<$WithHandleλShape & $PublicReadλShape & {
  "user": $.LinkDesc<$User, $.Cardinality.AtMostOne, {}, true, false,  false, false>;
  "photo": $.LinkDesc<$Image, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "bio": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "location": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<created_by[is Auditable]": $.LinkDesc<$Auditable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<created_by[is EditSuggestion]": $.LinkDesc<$EditSuggestion, $.Cardinality.Many, {}, false, false,  false, false>;
  "<created_by[is Image]": $.LinkDesc<$Image, $.Cardinality.Many, {}, false, false,  false, false>;
  "<created_by[is BlueskyPost]": $.LinkDesc<$BlueskyPost, $.Cardinality.Many, {}, false, false,  false, false>;
  "<created_by[is Note]": $.LinkDesc<$Note, $.Cardinality.Many, {}, false, false,  false, false>;
  "<created_by[is Resource]": $.LinkDesc<$Resource, $.Cardinality.Many, {}, false, false,  false, false>;
  "<created_by[is Source]": $.LinkDesc<$Source, $.Cardinality.Many, {}, false, false,  false, false>;
  "<users[is Source]": $.LinkDesc<$Source, $.Cardinality.Many, {}, false, false,  false, false>;
  "<created_by[is VegetableTip]": $.LinkDesc<$VegetableTip, $.Cardinality.Many, {}, false, false,  false, false>;
  "<created_by[is VegetableVariety]": $.LinkDesc<$VegetableVariety, $.Cardinality.Many, {}, false, false,  false, false>;
  "<created_by[is Vegetable]": $.LinkDesc<$Vegetable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<created_by[is VegetableFriendship]": $.LinkDesc<$VegetableFriendship, $.Cardinality.Many, {}, false, false,  false, false>;
  "<user_profile[is UserWishlist]": $.LinkDesc<$UserWishlist, $.Cardinality.Many, {}, false, false,  false, false>;
  "<reviewed_by[is EditSuggestion]": $.LinkDesc<$EditSuggestion, $.Cardinality.Many, {}, false, false,  false, false>;
  "<performed_by[is HistoryLog]": $.LinkDesc<$HistoryLog, $.Cardinality.Many, {}, false, false,  false, false>;
  "<created_by": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<performed_by": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<reviewed_by": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<user_profile": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<users": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $UserProfile = $.ObjectType<"default::UserProfile", $UserProfileλShape, null, [
  ...$WithHandle['__exclusives__'],
  ...$PublicRead['__exclusives__'],
  {user: {__element__: $User, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "default::UserProfile" | "default::current_user_profile">;
const $UserProfile = $.makeType<$UserProfile>(_.spec, "b8f9118e-1926-11ef-a4ff-599190c4313c", _.syntax.literal);

const UserProfile: $.$expr_PathNode<$.TypeSet<$UserProfile, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($UserProfile, $.Cardinality.Many), null);

export type $UserWishlistλShape = $.typeutil.flatten<$PublicReadλShape & {
  "user_profile": $.LinkDesc<$UserProfile, $.Cardinality.One, {}, false, false,  false, false>;
  "vegetable": $.LinkDesc<$Vegetable, $.Cardinality.One, {}, false, false,  false, false>;
  "status": $.PropertyDesc<$VegetableWishlistStatus, $.Cardinality.One, false, false, false, false>;
  "<wishlisted_by[is Vegetable]": $.LinkDesc<$Vegetable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<wishlisted_by": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $UserWishlist = $.ObjectType<"default::UserWishlist", $UserWishlistλShape, null, [
  ...$PublicRead['__exclusives__'],
  {user_profile: {__element__: $UserProfile, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },vegetable: {__element__: $Vegetable, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "default::UserWishlist">;
const $UserWishlist = $.makeType<$UserWishlist>(_.spec, "ba6e660e-1926-11ef-9706-351558ec79d9", _.syntax.literal);

const UserWishlist: $.$expr_PathNode<$.TypeSet<$UserWishlist, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($UserWishlist, $.Cardinality.Many), null);

export type $VegetableλShape = $.typeutil.flatten<$WithHandleλShape & $PublicReadλShape & $AuditableλShape & $UserCanInsertλShape & $AdminCanDoAnythingλShape & $ModeratorCanUpdateλShape & $PostableToBlueskyλShape & {
  "varieties": $.LinkDesc<$VegetableVariety, $.Cardinality.Many, {
    "@order_index": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne>;
  }, true, false, false, false>;
  "names": $.PropertyDesc<$.ArrayType<_std.$str>, $.Cardinality.One, false, false, false, false>;
  "scientific_names": $.PropertyDesc<$.ArrayType<_std.$str>, $.Cardinality.AtMostOne, false, false, false, false>;
  "searchable_names": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
  "content": $.PropertyDesc<_std.$json, $.Cardinality.AtMostOne, false, false, false, false>;
  "development_cycle_max": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne, false, false, false, false>;
  "development_cycle_min": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne, false, false, false, false>;
  "edible_parts": $.PropertyDesc<$EdiblePart, $.Cardinality.Many, false, false, false, false>;
  "gender": $.PropertyDesc<$Gender, $.Cardinality.AtMostOne, false, false, false, false>;
  "height_max": $.PropertyDesc<_std.$float32, $.Cardinality.AtMostOne, false, false, false, false>;
  "height_min": $.PropertyDesc<_std.$float32, $.Cardinality.AtMostOne, false, false, false, false>;
  "lifecycles": $.PropertyDesc<$VegetableLifeCycle, $.Cardinality.Many, false, false, false, false>;
  "origin": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "planting_methods": $.PropertyDesc<$PlantingMethod, $.Cardinality.Many, false, false, false, false>;
  "strata": $.PropertyDesc<$Stratum, $.Cardinality.Many, false, false, false, false>;
  "temperature_max": $.PropertyDesc<_std.$float32, $.Cardinality.AtMostOne, false, false, false, false>;
  "temperature_min": $.PropertyDesc<_std.$float32, $.Cardinality.AtMostOne, false, false, false, false>;
  "uses": $.PropertyDesc<$VegetableUsage, $.Cardinality.Many, false, false, false, false>;
  "photos": $.LinkDesc<$Image, $.Cardinality.Many, {
    "@order_index": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne>;
  }, false, false, false, false>;
  "sources": $.LinkDesc<$Source, $.Cardinality.Many, {
    "@order_index": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne>;
  }, false, false, false, false>;
  "tips": $.LinkDesc<$VegetableTip, $.Cardinality.Many, {
    "@order_index": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne>;
  }, true, false, false, false>;
  "friends": $.LinkDesc<$Vegetable, $.Cardinality.Many, {}, false, true,  false, false>;
  "related_notes": $.LinkDesc<$Note, $.Cardinality.Many, {}, false, true,  false, false>;
  "related_resources": $.LinkDesc<$Resource, $.Cardinality.Many, {}, false, true,  false, false>;
  "wishlisted_by": $.LinkDesc<$UserWishlist, $.Cardinality.Many, {}, false, true,  false, false>;
  "<vegetables[is VegetableFriendship]": $.LinkDesc<$VegetableFriendship, $.Cardinality.Many, {}, false, false,  false, false>;
  "<vegetable[is UserWishlist]": $.LinkDesc<$UserWishlist, $.Cardinality.Many, {}, false, false,  false, false>;
  "<target_object[is EditSuggestion]": $.LinkDesc<$EditSuggestion, $.Cardinality.Many, {}, false, false,  false, false>;
  "<friends[is Vegetable]": $.LinkDesc<$Vegetable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<related_to_vegetables[is Note]": $.LinkDesc<$Note, $.Cardinality.Many, {}, false, false,  false, false>;
  "<related_vegetables[is Resource]": $.LinkDesc<$Resource, $.Cardinality.Many, {}, false, false,  false, false>;
  "<friends": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<related_to_vegetables": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<related_vegetables": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<target_object": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<vegetable": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<vegetables": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Vegetable = $.ObjectType<"default::Vegetable", $VegetableλShape, null, [
  ...$WithHandle['__exclusives__'],
  ...$PublicRead['__exclusives__'],
  ...$Auditable['__exclusives__'],
  ...$UserCanInsert['__exclusives__'],
  ...$AdminCanDoAnything['__exclusives__'],
  ...$ModeratorCanUpdate['__exclusives__'],
  ...$PostableToBluesky['__exclusives__'],
  {tips: {__element__: $VegetableTip, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
  {varieties: {__element__: $VegetableVariety, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "default::Vegetable">;
const $Vegetable = $.makeType<$Vegetable>(_.spec, "b9e1b6aa-1926-11ef-a4f0-f7d0fc451707", _.syntax.literal);

const Vegetable: $.$expr_PathNode<$.TypeSet<$Vegetable, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Vegetable, $.Cardinality.Many), null);

export type $VegetableFriendshipλShape = $.typeutil.flatten<$AuditableλShape & $PublicReadλShape & $UserCanInsertλShape & $AdminCanDoAnythingλShape & {
  "vegetables": $.LinkDesc<$Vegetable, $.Cardinality.AtLeastOne, {}, false, false,  true, false>;
  "unique_key": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, true, false>;
}>;
type $VegetableFriendship = $.ObjectType<"default::VegetableFriendship", $VegetableFriendshipλShape, null, [
  ...$Auditable['__exclusives__'],
  ...$PublicRead['__exclusives__'],
  ...$UserCanInsert['__exclusives__'],
  ...$AdminCanDoAnything['__exclusives__'],
], "default::VegetableFriendship">;
const $VegetableFriendship = $.makeType<$VegetableFriendship>(_.spec, "ba519204-1926-11ef-aa4c-c174b1789b30", _.syntax.literal);

const VegetableFriendship: $.$expr_PathNode<$.TypeSet<$VegetableFriendship, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($VegetableFriendship, $.Cardinality.Many), null);

export type $VegetableTipλShape = $.typeutil.flatten<$WithHandleλShape & $PublicReadλShape & $AuditableλShape & $UserCanInsertλShape & $AdminCanDoAnythingλShape & {
  "content": $.PropertyDesc<_std.$json, $.Cardinality.One, false, false, false, false>;
  "subjects": $.PropertyDesc<$TipSubject, $.Cardinality.AtLeastOne, false, false, false, false>;
  "sources": $.LinkDesc<$Source, $.Cardinality.Many, {
    "@order_index": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne>;
  }, false, false, false, false>;
  "<tips[is Vegetable]": $.LinkDesc<$Vegetable, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "<tips": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $VegetableTip = $.ObjectType<"default::VegetableTip", $VegetableTipλShape, null, [
  ...$WithHandle['__exclusives__'],
  ...$PublicRead['__exclusives__'],
  ...$Auditable['__exclusives__'],
  ...$UserCanInsert['__exclusives__'],
  ...$AdminCanDoAnything['__exclusives__'],
], "default::VegetableTip">;
const $VegetableTip = $.makeType<$VegetableTip>(_.spec, "b9993ea2-1926-11ef-80c6-df13c8c83a49", _.syntax.literal);

const VegetableTip: $.$expr_PathNode<$.TypeSet<$VegetableTip, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($VegetableTip, $.Cardinality.Many), null);

export type $VegetableVarietyλShape = $.typeutil.flatten<$WithHandleλShape & $PublicReadλShape & $AuditableλShape & $UserCanInsertλShape & $AdminCanDoAnythingλShape & {
  "names": $.PropertyDesc<$.ArrayType<_std.$str>, $.Cardinality.One, false, false, false, false>;
  "photos": $.LinkDesc<$Image, $.Cardinality.Many, {
    "@order_index": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne>;
  }, false, false, false, false>;
  "<varieties[is Vegetable]": $.LinkDesc<$Vegetable, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "<varieties": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $VegetableVariety = $.ObjectType<"default::VegetableVariety", $VegetableVarietyλShape, null, [
  ...$WithHandle['__exclusives__'],
  ...$PublicRead['__exclusives__'],
  ...$Auditable['__exclusives__'],
  ...$UserCanInsert['__exclusives__'],
  ...$AdminCanDoAnything['__exclusives__'],
], "default::VegetableVariety">;
const $VegetableVariety = $.makeType<$VegetableVariety>(_.spec, "b9b8396a-1926-11ef-a3d3-a1bda95eb269", _.syntax.literal);

const VegetableVariety: $.$expr_PathNode<$.TypeSet<$VegetableVariety, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($VegetableVariety, $.Cardinality.Many), null);

export type $current_userλShape = $.typeutil.flatten<$UserλShape & {
}>;
type $current_user = $.ObjectType<"default::current_user", $current_userλShape, null, [
  ...$User['__exclusives__'],
], "default::current_user">;
const $current_user = $.makeType<$current_user>(_.spec, "fca149c0-09af-11f0-905d-81ccb3f4f7a5", _.syntax.literal);

const current_user: $.$expr_PathNode<$.TypeSet<$current_user, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($current_user, $.Cardinality.Many), null);

export type $current_user_profileλShape = $.typeutil.flatten<$UserProfileλShape & {
}>;
type $current_user_profile = $.ObjectType<"default::current_user_profile", $current_user_profileλShape, null, [
  ...$UserProfile['__exclusives__'],
], "default::current_user_profile">;
const $current_user_profile = $.makeType<$current_user_profile>(_.spec, "0648fa6d-11a3-11f0-b354-b307c68b134d", _.syntax.literal);

const current_user_profile: $.$expr_PathNode<$.TypeSet<$current_user_profile, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($current_user_profile, $.Cardinality.Many), null);

const $default__globals: {  current_user: _.syntax.$expr_Global<
              // "default::current_user",
              $current_user,
              $.Cardinality.AtMostOne
              >,  current_user_profile: _.syntax.$expr_Global<
              // "default::current_user_profile",
              $current_user_profile,
              $.Cardinality.AtMostOne
              >} = {  current_user: _.syntax.makeGlobal(
              "default::current_user",
              $.makeType(_.spec, "fca149c0-09af-11f0-905d-81ccb3f4f7a5", _.syntax.literal),
              $.Cardinality.AtMostOne) as any,  current_user_profile: _.syntax.makeGlobal(
              "default::current_user_profile",
              $.makeType(_.spec, "0648fa6d-11a3-11f0-b354-b307c68b134d", _.syntax.literal),
              $.Cardinality.AtMostOne) as any};



export { EdiblePart, EditSuggestionStatus, Gender, HistoryAction, NotePublishStatus, NoteType, PlantingMethod, ResourceFormat, Role, SourceType, Stratum, TipSubject, VegetableLifeCycle, VegetableUsage, VegetableWishlistStatus, $AdminCanDoAnything, AdminCanDoAnything, $Auditable, Auditable, $BlueskyPost, BlueskyPost, $UserCanInsert, UserCanInsert, $PublicRead, PublicRead, $ModeratorCanUpdate, ModeratorCanUpdate, $EditSuggestion, EditSuggestion, $HistoryLog, HistoryLog, $UserCanUpdate, UserCanUpdate, $Image, Image, $WithHandle, WithHandle, $PostableToBluesky, PostableToBluesky, $Note, Note, $WithTags, WithTags, $Resource, Resource, $Source, Source, $Tag, Tag, $User, User, $UserCanSelect, UserCanSelect, $UserProfile, UserProfile, $UserWishlist, UserWishlist, $Vegetable, Vegetable, $VegetableFriendship, VegetableFriendship, $VegetableTip, VegetableTip, $VegetableVariety, VegetableVariety, $current_user, current_user, $current_user_profile, current_user_profile };

type __defaultExports = {
  "EdiblePart": typeof EdiblePart;
  "EditSuggestionStatus": typeof EditSuggestionStatus;
  "Gender": typeof Gender;
  "HistoryAction": typeof HistoryAction;
  "NotePublishStatus": typeof NotePublishStatus;
  "NoteType": typeof NoteType;
  "PlantingMethod": typeof PlantingMethod;
  "ResourceFormat": typeof ResourceFormat;
  "Role": typeof Role;
  "SourceType": typeof SourceType;
  "Stratum": typeof Stratum;
  "TipSubject": typeof TipSubject;
  "VegetableLifeCycle": typeof VegetableLifeCycle;
  "VegetableUsage": typeof VegetableUsage;
  "VegetableWishlistStatus": typeof VegetableWishlistStatus;
  "AdminCanDoAnything": typeof AdminCanDoAnything;
  "Auditable": typeof Auditable;
  "BlueskyPost": typeof BlueskyPost;
  "UserCanInsert": typeof UserCanInsert;
  "PublicRead": typeof PublicRead;
  "ModeratorCanUpdate": typeof ModeratorCanUpdate;
  "EditSuggestion": typeof EditSuggestion;
  "HistoryLog": typeof HistoryLog;
  "UserCanUpdate": typeof UserCanUpdate;
  "Image": typeof Image;
  "WithHandle": typeof WithHandle;
  "PostableToBluesky": typeof PostableToBluesky;
  "Note": typeof Note;
  "WithTags": typeof WithTags;
  "Resource": typeof Resource;
  "Source": typeof Source;
  "Tag": typeof Tag;
  "User": typeof User;
  "UserCanSelect": typeof UserCanSelect;
  "UserProfile": typeof UserProfile;
  "UserWishlist": typeof UserWishlist;
  "Vegetable": typeof Vegetable;
  "VegetableFriendship": typeof VegetableFriendship;
  "VegetableTip": typeof VegetableTip;
  "VegetableVariety": typeof VegetableVariety;
  "current_user": typeof current_user;
  "current_user_profile": typeof current_user_profile;
  "global": typeof $default__globals
};
const __defaultExports: __defaultExports = {
  "EdiblePart": EdiblePart,
  "EditSuggestionStatus": EditSuggestionStatus,
  "Gender": Gender,
  "HistoryAction": HistoryAction,
  "NotePublishStatus": NotePublishStatus,
  "NoteType": NoteType,
  "PlantingMethod": PlantingMethod,
  "ResourceFormat": ResourceFormat,
  "Role": Role,
  "SourceType": SourceType,
  "Stratum": Stratum,
  "TipSubject": TipSubject,
  "VegetableLifeCycle": VegetableLifeCycle,
  "VegetableUsage": VegetableUsage,
  "VegetableWishlistStatus": VegetableWishlistStatus,
  "AdminCanDoAnything": AdminCanDoAnything,
  "Auditable": Auditable,
  "BlueskyPost": BlueskyPost,
  "UserCanInsert": UserCanInsert,
  "PublicRead": PublicRead,
  "ModeratorCanUpdate": ModeratorCanUpdate,
  "EditSuggestion": EditSuggestion,
  "HistoryLog": HistoryLog,
  "UserCanUpdate": UserCanUpdate,
  "Image": Image,
  "WithHandle": WithHandle,
  "PostableToBluesky": PostableToBluesky,
  "Note": Note,
  "WithTags": WithTags,
  "Resource": Resource,
  "Source": Source,
  "Tag": Tag,
  "User": User,
  "UserCanSelect": UserCanSelect,
  "UserProfile": UserProfile,
  "UserWishlist": UserWishlist,
  "Vegetable": Vegetable,
  "VegetableFriendship": VegetableFriendship,
  "VegetableTip": VegetableTip,
  "VegetableVariety": VegetableVariety,
  "current_user": current_user,
  "current_user_profile": current_user_profile,
  "global": $default__globals
};
export default __defaultExports;
