import { Effect } from "effect"
// This file was autogenerated by `migrate.ts` based on `src/db/migrations-sql/20261008185154_initial.sql`
import { SqlClient } from "effect/sql"

export default Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient

  yield* sql`-- Create "auth_subjects" table
CREATE TABLE \`auth_subjects\` (
  \`id\` text NOT NULL,
  \`name\` text NOT NULL,
  \`email\` text NOT NULL,
  \`is_email_verified\` integer NOT NULL,
  \`image\` text NULL,
  \`active\` integer NOT NULL DEFAULT 1,
  \`security_revision\` text NOT NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  PRIMARY KEY (\`id\`)
)`

  yield* sql`-- Create index "auth_subjects_email" to table: "auth_subjects"
CREATE UNIQUE INDEX \`auth_subjects_email\` ON \`auth_subjects\` (\`email\`)`

  yield* sql`-- Create "auth_oauth_flows" table
CREATE TABLE \`auth_oauth_flows\` (
  \`state\` text NOT NULL,
  \`flow_id\` text NOT NULL,
  \`provider\` text NOT NULL,
  \`binding_verifier\` text NOT NULL,
  \`nonce\` text NOT NULL,
  \`pkce_verifier\` text NOT NULL,
  \`link_auth_subject_id\` text NULL,
  \`expires_at\` integer NOT NULL,
  PRIMARY KEY (\`state\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`link_auth_subject_id\`) REFERENCES \`auth_subjects\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create index "auth_oauth_flows_flow_id" to table: "auth_oauth_flows"
CREATE UNIQUE INDEX \`auth_oauth_flows_flow_id\` ON \`auth_oauth_flows\` (\`flow_id\`)`

  yield* sql`-- Create "auth_oauth_identities" table
CREATE TABLE \`auth_oauth_identities\` (
  \`provider\` text NOT NULL,
  \`issuer\` text NOT NULL,
  \`subject\` text NOT NULL,
  \`auth_subject_id\` text NOT NULL,
  \`credential_id\` text NOT NULL,
  CONSTRAINT \`0\` FOREIGN KEY (\`auth_subject_id\`) REFERENCES \`auth_subjects\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create index "auth_oauth_identities_credential_id" to table: "auth_oauth_identities"
CREATE UNIQUE INDEX \`auth_oauth_identities_credential_id\` ON \`auth_oauth_identities\` (\`credential_id\`)`

  yield* sql`-- Create index "auth_oauth_identities_provider_issuer_subject" to table: "auth_oauth_identities"
CREATE UNIQUE INDEX \`auth_oauth_identities_provider_issuer_subject\` ON \`auth_oauth_identities\` (\`provider\`, \`issuer\`, \`subject\`)`

  yield* sql`-- Create index "auth_oauth_identities_auth_subject_id_idx" to table: "auth_oauth_identities"
CREATE INDEX \`auth_oauth_identities_auth_subject_id_idx\` ON \`auth_oauth_identities\` (\`auth_subject_id\`)`

  yield* sql`-- Create "auth_identifiers" table
CREATE TABLE \`auth_identifiers\` (
  \`namespace\` text NOT NULL,
  \`value\` text NOT NULL,
  \`auth_subject_id\` text NOT NULL,
  \`revision\` text NOT NULL,
  \`verified_at\` integer NULL,
  \`active\` integer NOT NULL,
  CONSTRAINT \`0\` FOREIGN KEY (\`auth_subject_id\`) REFERENCES \`auth_subjects\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create index "auth_identifiers_namespace_value" to table: "auth_identifiers"
CREATE UNIQUE INDEX \`auth_identifiers_namespace_value\` ON \`auth_identifiers\` (\`namespace\`, \`value\`)`

  yield* sql`-- Create "auth_credentials" table
CREATE TABLE \`auth_credentials\` (
  \`credential_id\` text NOT NULL,
  \`auth_subject_id\` text NOT NULL,
  \`revision\` text NOT NULL,
  \`active\` integer NOT NULL,
  CONSTRAINT \`0\` FOREIGN KEY (\`auth_subject_id\`) REFERENCES \`auth_subjects\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create index "auth_credentials_credential_id" to table: "auth_credentials"
CREATE UNIQUE INDEX \`auth_credentials_credential_id\` ON \`auth_credentials\` (\`credential_id\`)`

  yield* sql`-- Create index "auth_credentials_auth_subject_id_idx" to table: "auth_credentials"
CREATE INDEX \`auth_credentials_auth_subject_id_idx\` ON \`auth_credentials\` (\`auth_subject_id\`)`

  yield* sql`-- Create "auth_sessions" table
CREATE TABLE \`auth_sessions\` (
  \`session_id\` text NOT NULL,
  \`auth_subject_id\` text NOT NULL,
  \`digest\` text NOT NULL,
  \`version\` text NOT NULL,
  \`security_revision\` text NOT NULL,
  \`issued_at\` integer NOT NULL,
  \`expires_at\` integer NOT NULL,
  \`absolute_expires_at\` integer NOT NULL,
  \`record\` text NOT NULL,
  CONSTRAINT \`0\` FOREIGN KEY (\`auth_subject_id\`) REFERENCES \`auth_subjects\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create index "auth_sessions_session_id" to table: "auth_sessions"
CREATE UNIQUE INDEX \`auth_sessions_session_id\` ON \`auth_sessions\` (\`session_id\`)`

  yield* sql`-- Create index "auth_sessions_digest" to table: "auth_sessions"
CREATE UNIQUE INDEX \`auth_sessions_digest\` ON \`auth_sessions\` (\`digest\`)`

  yield* sql`-- Create index "auth_sessions_auth_subject_id_idx" to table: "auth_sessions"
CREATE INDEX \`auth_sessions_auth_subject_id_idx\` ON \`auth_sessions\` (\`auth_subject_id\`)`

  yield* sql`-- Create "auth_session_flows" table
CREATE TABLE \`auth_session_flows\` (
  \`flow_id\` text NOT NULL,
  \`auth_subject_id\` text NOT NULL,
  \`state\` text NOT NULL,
  \`pending_digest\` text NULL,
  \`dedup_until\` integer NOT NULL,
  CONSTRAINT \`0\` FOREIGN KEY (\`auth_subject_id\`) REFERENCES \`auth_subjects\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create index "auth_session_flows_flow_id" to table: "auth_session_flows"
CREATE UNIQUE INDEX \`auth_session_flows_flow_id\` ON \`auth_session_flows\` (\`flow_id\`)`

  yield* sql`-- Create "auth_email_credentials" table
CREATE TABLE \`auth_email_credentials\` (
  \`module_id\` text NOT NULL,
  \`auth_subject_id\` text NOT NULL,
  \`credential_id\` text NOT NULL,
  \`identifier_namespace\` text NOT NULL,
  \`identifier_value\` text NOT NULL,
  \`credential_revision\` text NOT NULL,
  \`active\` integer NOT NULL,
  CONSTRAINT \`0\` FOREIGN KEY (\`auth_subject_id\`) REFERENCES \`auth_subjects\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create index "auth_email_credentials_module_id_credential_id" to table: "auth_email_credentials"
CREATE UNIQUE INDEX \`auth_email_credentials_module_id_credential_id\` ON \`auth_email_credentials\` (\`module_id\`, \`credential_id\`)`

  yield* sql`-- Create index "auth_email_credentials_module_id_identifier_namespace_identifier_value" to table: "auth_email_credentials"
CREATE UNIQUE INDEX \`auth_email_credentials_module_id_identifier_namespace_identifier_value\` ON \`auth_email_credentials\` (\`module_id\`, \`identifier_namespace\`, \`identifier_value\`)`

  yield* sql`-- Create "auth_email_commands" table
CREATE TABLE \`auth_email_commands\` (
  \`module_id\` text NOT NULL,
  \`command_id\` text NOT NULL,
  \`action\` text NOT NULL,
  \`binding_digest\` text NOT NULL,
  \`retention_until\` integer NOT NULL
)`

  yield* sql`-- Create index "auth_email_commands_module_id_command_id" to table: "auth_email_commands"
CREATE UNIQUE INDEX \`auth_email_commands_module_id_command_id\` ON \`auth_email_commands\` (\`module_id\`, \`command_id\`)`

  yield* sql`-- Create "auth_proof_requests" table
CREATE TABLE \`auth_proof_requests\` (
  \`module_id\` text NOT NULL,
  \`request_id\` text NOT NULL,
  \`fingerprint\` text NOT NULL,
  \`proof_id\` text NOT NULL,
  \`purpose\` text NOT NULL,
  \`key_id\` text NOT NULL,
  \`created_at\` integer NOT NULL,
  \`retention_until\` integer NOT NULL,
  \`receipt\` text NOT NULL
)`

  yield* sql`-- Create index "auth_proof_requests_module_id_request_id" to table: "auth_proof_requests"
CREATE UNIQUE INDEX \`auth_proof_requests_module_id_request_id\` ON \`auth_proof_requests\` (\`module_id\`, \`request_id\`)`

  yield* sql`-- Create "auth_proof_series" table
CREATE TABLE \`auth_proof_series\` (
  \`module_id\` text NOT NULL,
  \`purpose\` text NOT NULL,
  \`scope_key\` text NOT NULL,
  \`active_proof_id\` text NULL,
  \`last_issue_at\` integer NULL,
  \`version\` text NOT NULL
)`

  yield* sql`-- Create index "auth_proof_series_module_id_purpose_scope_key" to table: "auth_proof_series"
CREATE UNIQUE INDEX \`auth_proof_series_module_id_purpose_scope_key\` ON \`auth_proof_series\` (\`module_id\`, \`purpose\`, \`scope_key\`)`

  yield* sql`-- Create "auth_proof_generations" table
CREATE TABLE \`auth_proof_generations\` (
  \`module_id\` text NOT NULL,
  \`purpose\` text NOT NULL,
  \`proof_id\` text NOT NULL,
  \`request_id\` text NOT NULL,
  \`series_key\` text NOT NULL,
  \`delivery_id\` text NOT NULL,
  \`binding\` text NOT NULL,
  \`verifier_key_id\` text NOT NULL,
  \`verifier_digest\` text NOT NULL,
  \`issued_at\` integer NOT NULL,
  \`expires_at\` integer NOT NULL,
  \`version\` text NOT NULL,
  \`state\` text NOT NULL,
  \`send_count\` integer NOT NULL,
  \`delivery_state\` text NOT NULL,
  \`claim_version\` text NULL,
  \`claim_deadline\` integer NULL,
  \`retry_at\` integer NULL,
  \`delivery_retry_millis\` integer NOT NULL,
  \`retention_until\` integer NOT NULL,
  \`fingerprint\` text NOT NULL
)`

  yield* sql`-- Create index "auth_proof_generations_module_id_proof_id" to table: "auth_proof_generations"
CREATE UNIQUE INDEX \`auth_proof_generations_module_id_proof_id\` ON \`auth_proof_generations\` (\`module_id\`, \`proof_id\`)`

  yield* sql`-- Create index "auth_proof_generations_module_id_delivery_id" to table: "auth_proof_generations"
CREATE UNIQUE INDEX \`auth_proof_generations_module_id_delivery_id\` ON \`auth_proof_generations\` (\`module_id\`, \`delivery_id\`)`

  yield* sql`-- Create "auth_proof_continuations" table
CREATE TABLE \`auth_proof_continuations\` (
  \`module_id\` text NOT NULL,
  \`purpose\` text NOT NULL,
  \`continuation_id\` text NOT NULL,
  \`digest\` text NOT NULL,
  \`proof_id\` text NOT NULL,
  \`series_key\` text NOT NULL,
  \`binding\` text NOT NULL,
  \`expires_at\` integer NOT NULL,
  \`consumed\` integer NOT NULL,
  \`version\` text NOT NULL,
  \`retention_until\` integer NOT NULL
)`

  yield* sql`-- Create index "auth_proof_continuations_module_id_continuation_id" to table: "auth_proof_continuations"
CREATE UNIQUE INDEX \`auth_proof_continuations_module_id_continuation_id\` ON \`auth_proof_continuations\` (\`module_id\`, \`continuation_id\`)`

  yield* sql`-- Create index "auth_proof_continuations_module_id_digest" to table: "auth_proof_continuations"
CREATE UNIQUE INDEX \`auth_proof_continuations_module_id_digest\` ON \`auth_proof_continuations\` (\`module_id\`, \`digest\`)`

  yield* sql`-- Create "auth_proof_scopes" table
CREATE TABLE \`auth_proof_scopes\` (
  \`module_id\` text NOT NULL,
  \`purpose\` text NOT NULL,
  \`action\` text NOT NULL,
  \`scope_kind\` text NOT NULL,
  \`scope_key\` text NOT NULL
)`

  yield* sql`-- Create index "auth_proof_scopes_module_id_purpose_action_scope_kind_scope_key" to table: "auth_proof_scopes"
CREATE UNIQUE INDEX \`auth_proof_scopes_module_id_purpose_action_scope_kind_scope_key\` ON \`auth_proof_scopes\` (\`module_id\`, \`purpose\`, \`action\`, \`scope_kind\`, \`scope_key\`)`

  yield* sql`-- Create "auth_proof_abuse" table
CREATE TABLE \`auth_proof_abuse\` (
  \`module_id\` text NOT NULL,
  \`purpose\` text NOT NULL,
  \`action\` text NOT NULL,
  \`scope_kind\` text NOT NULL,
  \`scope_key\` text NOT NULL,
  \`command_id\` text NOT NULL,
  \`occurred_at\` integer NOT NULL,
  \`retention_until\` integer NOT NULL
)`

  yield* sql`-- Create index "auth_proof_abuse_module_id_action_scope_kind_scope_key_command_id" to table: "auth_proof_abuse"
CREATE UNIQUE INDEX \`auth_proof_abuse_module_id_action_scope_kind_scope_key_command_id\` ON \`auth_proof_abuse\` (\`module_id\`, \`action\`, \`scope_kind\`, \`scope_key\`, \`command_id\`)`

  yield* sql`-- Create "auth_proof_failures" table
CREATE TABLE \`auth_proof_failures\` (
  \`module_id\` text NOT NULL,
  \`purpose\` text NOT NULL,
  \`series_key\` text NOT NULL,
  \`command_id\` text NOT NULL,
  \`occurred_at\` integer NOT NULL,
  \`retention_until\` integer NOT NULL
)`

  yield* sql`-- Create index "auth_proof_failures_module_id_series_key_command_id" to table: "auth_proof_failures"
CREATE UNIQUE INDEX \`auth_proof_failures_module_id_series_key_command_id\` ON \`auth_proof_failures\` (\`module_id\`, \`series_key\`, \`command_id\`)`

  yield* sql`-- Create "auth_proof_commands" table
CREATE TABLE \`auth_proof_commands\` (
  \`module_id\` text NOT NULL,
  \`command_id\` text NOT NULL,
  \`kind\` text NOT NULL,
  \`decision\` text NOT NULL,
  \`retention_until\` integer NOT NULL
)`

  yield* sql`-- Create index "auth_proof_commands_module_id_command_id" to table: "auth_proof_commands"
CREATE UNIQUE INDEX \`auth_proof_commands_module_id_command_id\` ON \`auth_proof_commands\` (\`module_id\`, \`command_id\`)`

  yield* sql`-- Create "profiles" table
CREATE TABLE \`profiles\` (
  \`id\` text NOT NULL,
  \`type\` text NOT NULL,
  \`handle\` text NOT NULL,
  \`name\` text NOT NULL,
  \`bio\` json NULL,
  \`location\` text NULL,
  \`photo_id\` text NULL,
  \`visibility\` text NOT NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`photo_id\`) REFERENCES \`media_assets\` (\`id\`) ON UPDATE NO ACTION ON DELETE SET NULL
)`

  yield* sql`-- Create index "profiles_handle" to table: "profiles"
CREATE UNIQUE INDEX \`profiles_handle\` ON \`profiles\` (\`handle\`)`

  yield* sql`-- Create index "idx_profiles_handle" to table: "profiles"
CREATE INDEX \`idx_profiles_handle\` ON \`profiles\` (\`handle\`)`

  yield* sql`-- Create "people" table
CREATE TABLE \`people\` (
  \`id\` text NULL,
  \`access_level\` text NOT NULL,
  \`access_set_by_id\` text NULL,
  \`access_set_at\` text NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`access_set_by_id\`) REFERENCES \`profiles\` (\`id\`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT \`1\` FOREIGN KEY (\`id\`) REFERENCES \`auth_subjects\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`2\` FOREIGN KEY (\`id\`) REFERENCES \`profiles\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create "organizations" table
CREATE TABLE \`organizations\` (
  \`id\` text NULL,
  \`type\` text NOT NULL,
  \`members_visibility\` text NOT NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`id\`) REFERENCES \`profiles\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create "organization_memberships" table
CREATE TABLE \`organization_memberships\` (
  \`person_id\` text NOT NULL,
  \`organization_id\` text NOT NULL,
  \`access_level\` text NOT NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  PRIMARY KEY (\`person_id\`, \`organization_id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organizations\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`1\` FOREIGN KEY (\`person_id\`) REFERENCES \`people\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
) WITHOUT ROWID`

  yield* sql`-- Create "organization_invitations" table
CREATE TABLE \`organization_invitations\` (
  \`id\` text NOT NULL,
  \`organization_id\` text NOT NULL,
  \`email\` text NOT NULL,
  \`access_level\` text NOT NULL,
  \`status\` text NOT NULL,
  \`created_by_id\` text NOT NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`people\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`1\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organizations\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create index "organization_invitations_organization_id_email" to table: "organization_invitations"
CREATE UNIQUE INDEX \`organization_invitations_organization_id_email\` ON \`organization_invitations\` (\`organization_id\`, \`email\`)`

  yield* sql`-- Create "tags" table
CREATE TABLE \`tags\` (
  \`id\` text NULL,
  \`handle\` text NOT NULL,
  \`names\` json NOT NULL,
  \`description\` json NULL,
  \`cluster\` text NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  \`created_by_id\` text NULL,
  PRIMARY KEY (\`id\`)
)`

  yield* sql`-- Create index "tags_handle" to table: "tags"
CREATE UNIQUE INDEX \`tags_handle\` ON \`tags\` (\`handle\`)`

  yield* sql`-- Create index "idx_tags_handle" to table: "tags"
CREATE INDEX \`idx_tags_handle\` ON \`tags\` (\`handle\`)`

  yield* sql`-- Create "suggested_tags" table
CREATE TABLE \`suggested_tags\` (
  \`id\` text NULL,
  \`handle\` text NOT NULL,
  \`names\` json NOT NULL,
  \`status\` text NOT NULL,
  \`approved_tag_id\` text NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`approved_tag_id\`) REFERENCES \`tags\` (\`id\`) ON UPDATE NO ACTION ON DELETE SET NULL
)`

  yield* sql`-- Create index "suggested_tags_handle" to table: "suggested_tags"
CREATE UNIQUE INDEX \`suggested_tags_handle\` ON \`suggested_tags\` (\`handle\`)`

  yield* sql`-- Create "suggested_tag_sources" table
CREATE TABLE \`suggested_tag_sources\` (
  \`suggested_tag_id\` text NOT NULL,
  \`publication_id\` text NOT NULL,
  PRIMARY KEY (\`suggested_tag_id\`, \`publication_id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`publication_id\`) REFERENCES \`publication_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`1\` FOREIGN KEY (\`suggested_tag_id\`) REFERENCES \`suggested_tags\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
) WITHOUT ROWID`

  yield* sql`-- Create "media_assets" table
CREATE TABLE \`media_assets\` (
  \`id\` text NULL,
  \`format\` text NOT NULL,
  \`content_type\` text NULL,
  \`byte_size\` integer NULL,
  \`category\` text NULL,
  \`descriptions\` json NULL,
  \`metadata\` json NOT NULL,
  \`moderation_status\` text NOT NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  \`owner_profile_id\` text NOT NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`owner_profile_id\`) REFERENCES \`profiles\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create "media_asset_credits" table
CREATE TABLE \`media_asset_credits\` (
  \`media_asset_id\` text NOT NULL,
  \`order_index\` integer NOT NULL,
  \`credit_line\` text NULL,
  \`credit_url\` text NULL,
  \`person_id\` text NULL,
  PRIMARY KEY (\`media_asset_id\`, \`order_index\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`person_id\`) REFERENCES \`people\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`1\` FOREIGN KEY (\`media_asset_id\`) REFERENCES \`media_assets\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
) WITHOUT ROWID`

  yield* sql`-- Create "wiki_article_crdts" table
CREATE TABLE \`wiki_article_crdts\` (
  \`id\` text NOT NULL,
  \`status\` text NOT NULL,
  \`crdt_snapshot\` blob NOT NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  PRIMARY KEY (\`id\`)
) WITHOUT ROWID`

  yield* sql`-- Create "wiki_article_revisions" table
CREATE TABLE \`wiki_article_revisions\` (
  \`id\` text NULL,
  \`wiki_article_id\` text NOT NULL,
  \`created_by_id\` text NULL,
  \`crdt_update\` blob NOT NULL,
  \`from_crdt_frontier\` json NOT NULL,
  \`evaluation\` text NOT NULL,
  \`evaluation_reason\` text NULL,
  \`has_media_selection\` integer NOT NULL DEFAULT 0,
  \`evaluated_by_id\` text NULL,
  \`evaluated_at\` text NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`evaluated_by_id\`) REFERENCES \`people\` (\`id\`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT \`1\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`people\` (\`id\`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT \`2\` FOREIGN KEY (\`wiki_article_id\`) REFERENCES \`wiki_article_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CHECK (has_media_selection IN (0, 1))
)`

  yield* sql`-- Create index "idx_wiki_article_revisions_article_evaluation" to table: "wiki_article_revisions"
CREATE INDEX \`idx_wiki_article_revisions_article_evaluation\` ON \`wiki_article_revisions\` (\`wiki_article_id\`, \`evaluation\`)`

  yield* sql`-- Create "wiki_article_revision_media_assets" table
CREATE TABLE \`wiki_article_revision_media_assets\` (
  \`wiki_article_revision_id\` text NOT NULL,
  \`media_asset_id\` text NOT NULL,
  \`category\` text NULL,
  \`has_category_override\` integer NOT NULL DEFAULT 0,
  \`descriptions\` json NULL,
  PRIMARY KEY (\`wiki_article_revision_id\`, \`media_asset_id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`media_asset_id\`) REFERENCES \`media_assets\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`1\` FOREIGN KEY (\`wiki_article_revision_id\`) REFERENCES \`wiki_article_revisions\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CHECK (has_category_override IN (0, 1))
) WITHOUT ROWID`

  yield* sql`-- Create index "idx_wiki_article_revision_media_assets_media_asset" to table: "wiki_article_revision_media_assets"
CREATE INDEX \`idx_wiki_article_revision_media_assets_media_asset\` ON \`wiki_article_revision_media_assets\` (\`media_asset_id\`)`

  yield* sql`-- Create "wiki_articles" table
CREATE TABLE \`wiki_articles\` (
  \`id\` text NULL,
  \`kind\` text NOT NULL,
  \`status\` text NOT NULL,
  \`attributes\` json NOT NULL,
  \`current_crdt_frontier\` json NOT NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`id\`) REFERENCES \`wiki_article_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create index "idx_wiki_articles_id_kind" to table: "wiki_articles"
CREATE UNIQUE INDEX \`idx_wiki_articles_id_kind\` ON \`wiki_articles\` (\`id\`, \`kind\`)`

  yield* sql`-- Create index "idx_wiki_articles_kind_status" to table: "wiki_articles"
CREATE INDEX \`idx_wiki_articles_kind_status\` ON \`wiki_articles\` (\`kind\`, \`status\`)`

  yield* sql`-- Create "wiki_article_translations" table
CREATE TABLE \`wiki_article_translations\` (
  \`wiki_article_id\` text NOT NULL,
  \`kind\` text NOT NULL,
  \`locale\` text NOT NULL,
  \`common_names\` json NOT NULL,
  \`searchable_names\` text NOT NULL,
  \`content\` json NULL,
  \`content_plain_text\` text NOT NULL,
  \`grammatical_gender\` text NULL,
  \`origin\` text NULL,
  PRIMARY KEY (\`wiki_article_id\`, \`locale\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`wiki_article_id\`, \`kind\`) REFERENCES \`wiki_articles\` (\`id\`, \`kind\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CHECK (
    kind = 'PLANT'
    OR origin IS NULL
  )
) WITHOUT ROWID`

  yield* sql`-- Create "wiki_article_handles" table
CREATE TABLE \`wiki_article_handles\` (
  \`wiki_article_id\` text NOT NULL,
  \`kind\` text NOT NULL,
  \`handle\` text NOT NULL,
  \`locale\` text NOT NULL,
  PRIMARY KEY (\`wiki_article_id\`, \`kind\`, \`handle\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`wiki_article_id\`) REFERENCES \`wiki_article_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
) WITHOUT ROWID`

  yield* sql`-- Create index "wiki_article_handles_kind_handle" to table: "wiki_article_handles"
CREATE UNIQUE INDEX \`wiki_article_handles_kind_handle\` ON \`wiki_article_handles\` (\`kind\`, \`handle\`)`

  yield* sql`-- Create "wiki_article_media_assets" table
CREATE TABLE \`wiki_article_media_assets\` (
  \`wiki_article_id\` text NOT NULL,
  \`media_asset_id\` text NOT NULL,
  PRIMARY KEY (\`wiki_article_id\`, \`media_asset_id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`media_asset_id\`) REFERENCES \`media_assets\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`1\` FOREIGN KEY (\`wiki_article_id\`) REFERENCES \`wiki_article_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
) WITHOUT ROWID`

  yield* sql`-- Create "publication_crdts" table
CREATE TABLE \`publication_crdts\` (
  \`id\` text NOT NULL,
  \`crdt_snapshot\` blob NOT NULL,
  \`classification\` json NULL,
  \`owner_profile_id\` text NOT NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`owner_profile_id\`) REFERENCES \`profiles\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
) WITHOUT ROWID`

  yield* sql`-- Create "publication_commits" table
CREATE TABLE \`publication_commits\` (
  \`id\` text NULL,
  \`publication_id\` text NOT NULL,
  \`created_by_id\` text NULL,
  \`from_crdt_frontier\` json NOT NULL,
  \`crdt_update\` blob NOT NULL,
  \`updated_at\` text NOT NULL,
  \`created_at\` text NOT NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`people\` (\`id\`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT \`1\` FOREIGN KEY (\`publication_id\`) REFERENCES \`publication_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create "publications" table
CREATE TABLE \`publications\` (
  \`id\` text NULL,
  \`current_crdt_frontier\` json NOT NULL,
  \`handle\` text NOT NULL,
  \`visibility\` text NULL,
  \`published_at\` text NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  \`owner_profile_id\` text NOT NULL,
  \`kind\` text NOT NULL,
  \`start_date\` text NULL,
  \`end_date\` text NULL,
  \`location_or_url\` text NULL,
  \`attendance_mode\` text NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`owner_profile_id\`) REFERENCES \`profiles\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`1\` FOREIGN KEY (\`id\`) REFERENCES \`publication_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create index "publications_handle" to table: "publications"
CREATE UNIQUE INDEX \`publications_handle\` ON \`publications\` (\`handle\`)`

  yield* sql`-- Create index "idx_publications_handle" to table: "publications"
CREATE INDEX \`idx_publications_handle\` ON \`publications\` (\`handle\`)`

  yield* sql`-- Create index "idx_publications_kind" to table: "publications"
CREATE INDEX \`idx_publications_kind\` ON \`publications\` (\`kind\`)`

  yield* sql`-- Create "publication_translations" table
CREATE TABLE \`publication_translations\` (
  \`publication_id\` text NOT NULL,
  \`locale\` text NOT NULL,
  \`content\` json NOT NULL,
  \`content_plain_text\` text NOT NULL,
  \`translated_at_crdt_frontier\` json NOT NULL,
  \`translation_source\` text NOT NULL,
  \`original_locale\` text NOT NULL,
  PRIMARY KEY (\`publication_id\`, \`locale\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`publication_id\`) REFERENCES \`publication_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
) WITHOUT ROWID`

  yield* sql`-- Create "publication_tags" table
CREATE TABLE \`publication_tags\` (
  \`publication_id\` text NOT NULL,
  \`tag_id\` text NOT NULL,
  \`extraction_text\` text NULL,
  PRIMARY KEY (\`publication_id\`, \`tag_id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`tag_id\`) REFERENCES \`tags\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`1\` FOREIGN KEY (\`publication_id\`) REFERENCES \`publication_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
) WITHOUT ROWID`

  yield* sql`-- Create "publication_media_assets" table
CREATE TABLE \`publication_media_assets\` (
  \`publication_id\` text NOT NULL,
  \`media_asset_id\` text NOT NULL,
  PRIMARY KEY (\`publication_id\`, \`media_asset_id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`media_asset_id\`) REFERENCES \`media_assets\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`1\` FOREIGN KEY (\`publication_id\`) REFERENCES \`publication_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
) WITHOUT ROWID`

  yield* sql`-- Create "publication_wiki_articles" table
CREATE TABLE \`publication_wiki_articles\` (
  \`publication_id\` text NOT NULL,
  \`wiki_article_id\` text NOT NULL,
  \`extraction_text\` text NULL,
  PRIMARY KEY (\`publication_id\`, \`wiki_article_id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`wiki_article_id\`) REFERENCES \`wiki_article_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`1\` FOREIGN KEY (\`publication_id\`) REFERENCES \`publication_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
) WITHOUT ROWID`

  yield* sql`-- Create "comment_crdts" table
CREATE TABLE \`comment_crdts\` (
  \`id\` text NULL,
  \`publication_id\` text NOT NULL,
  \`parent_comment_id\` text NULL,
  \`crdt_snapshot\` blob NOT NULL,
  \`owner_profile_id\` text NOT NULL,
  \`moderation_status\` text NOT NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`owner_profile_id\`) REFERENCES \`profiles\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`1\` FOREIGN KEY (\`parent_comment_id\`) REFERENCES \`comment_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`2\` FOREIGN KEY (\`publication_id\`) REFERENCES \`publication_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create "comment_commits" table
CREATE TABLE \`comment_commits\` (
  \`id\` text NULL,
  \`comment_id\` text NULL,
  \`created_by_id\` text NULL,
  \`from_crdt_frontier\` json NOT NULL,
  \`crdt_update\` blob NOT NULL,
  \`created_at\` text NOT NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`people\` (\`id\`) ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT \`1\` FOREIGN KEY (\`comment_id\`) REFERENCES \`comment_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create "comments" table
CREATE TABLE \`comments\` (
  \`id\` text NULL,
  \`publication_id\` text NOT NULL,
  \`parent_comment_id\` text NULL,
  \`current_crdt_frontier\` json NOT NULL,
  \`moderation_status\` text NOT NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  \`owner_profile_id\` text NOT NULL,
  PRIMARY KEY (\`id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`publication_id\`) REFERENCES \`publication_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`1\` FOREIGN KEY (\`owner_profile_id\`) REFERENCES \`profiles\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`2\` FOREIGN KEY (\`id\`) REFERENCES \`comment_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create "comment_translations" table
CREATE TABLE \`comment_translations\` (
  \`comment_id\` text NOT NULL,
  \`locale\` text NOT NULL,
  \`content\` json NOT NULL,
  \`content_plain_text\` text NOT NULL,
  \`translated_at_crdt_frontier\` json NOT NULL,
  \`translation_source\` text NOT NULL,
  \`original_locale\` text NOT NULL,
  PRIMARY KEY (\`comment_id\`, \`locale\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`comment_id\`) REFERENCES \`comment_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
) WITHOUT ROWID`

  yield* sql`-- Create "bookmarks_wiki_articles" table
CREATE TABLE \`bookmarks_wiki_articles\` (
  \`person_id\` text NOT NULL,
  \`wiki_article_id\` text NOT NULL,
  \`state\` text NOT NULL,
  PRIMARY KEY (\`person_id\`, \`wiki_article_id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`wiki_article_id\`) REFERENCES \`wiki_article_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT \`1\` FOREIGN KEY (\`person_id\`) REFERENCES \`people\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
) WITHOUT ROWID`

  yield* sql`-- Create "wiki_article_external_links" table
CREATE TABLE \`wiki_article_external_links\` (
  \`wiki_article_id\` text NOT NULL,
  \`locale\` text NOT NULL,
  \`url\` text NOT NULL,
  PRIMARY KEY (\`wiki_article_id\`, \`locale\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`wiki_article_id\`) REFERENCES \`wiki_article_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create "wiki_plant_taxonomy_group" table
CREATE TABLE \`wiki_plant_taxonomy_group\` (
  \`wiki_article_id\` text NOT NULL,
  \`gbif_taxon_id\` text NOT NULL,
  \`taxonomy_group\` text NULL,
  PRIMARY KEY (\`wiki_article_id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`wiki_article_id\`) REFERENCES \`wiki_article_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create index "idx_plant_taxon" to table: "wiki_plant_taxonomy_group"
CREATE INDEX \`idx_plant_taxon\` ON \`wiki_plant_taxonomy_group\` (\`gbif_taxon_id\`)`

  yield* sql`-- Create "wiki_plant_taxonomy_classification" table
CREATE TABLE \`wiki_plant_taxonomy_classification\` (
  \`wiki_article_id\` text NOT NULL,
  \`taxon_id\` text NOT NULL,
  \`scientific_name\` text NOT NULL,
  \`taxon_rank\` text NOT NULL,
  PRIMARY KEY (\`wiki_article_id\`, \`taxon_rank\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`wiki_article_id\`) REFERENCES \`wiki_article_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create index "idx_plant_classification" to table: "wiki_plant_taxonomy_classification"
CREATE INDEX \`idx_plant_classification\` ON \`wiki_plant_taxonomy_classification\` (\`taxon_rank\`, \`scientific_name\`)`

  yield* sql`-- Create "wiki_article_external_media" table
CREATE TABLE \`wiki_article_external_media\` (
  \`wiki_article_id\` text NOT NULL,
  \`media_url\` text NOT NULL,
  \`source_url\` text NOT NULL,
  \`credit_line\` text NOT NULL,
  \`license_url\` text NULL,
  PRIMARY KEY (\`wiki_article_id\`, \`media_url\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`wiki_article_id\`) REFERENCES \`wiki_article_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create "wiki_book_editions" table
CREATE TABLE \`wiki_book_editions\` (
  \`wiki_article_id\` text NOT NULL,
  \`provider\` text NOT NULL,
  \`external_id\` text NOT NULL,
  \`title\` text NOT NULL,
  \`publisher\` text NULL,
  \`publication_date\` text NULL,
  \`page_count\` integer NULL,
  \`isbn\` json NOT NULL,
  \`source_url\` text NOT NULL,
  PRIMARY KEY (\`wiki_article_id\`, \`provider\`, \`external_id\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`wiki_article_id\`) REFERENCES \`wiki_article_crdts\` (\`id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create "wiki_book_edition_languages" table
CREATE TABLE \`wiki_book_edition_languages\` (
  \`wiki_article_id\` text NOT NULL,
  \`provider\` text NOT NULL,
  \`external_id\` text NOT NULL,
  \`language\` text NOT NULL,
  PRIMARY KEY (\`wiki_article_id\`, \`provider\`, \`external_id\`, \`language\`),
  CONSTRAINT \`0\` FOREIGN KEY (\`wiki_article_id\`, \`provider\`, \`external_id\`) REFERENCES \`wiki_book_editions\` (\`wiki_article_id\`, \`provider\`, \`external_id\`) ON UPDATE NO ACTION ON DELETE CASCADE
)`

  yield* sql`-- Create index "idx_book_edition_language" to table: "wiki_book_edition_languages"
CREATE INDEX \`idx_book_edition_language\` ON \`wiki_book_edition_languages\` (\`language\`, \`wiki_article_id\`)`
})
