// Auto-generated by migrate.ts - do not edit
import * as _20261008185154_initial from "./20261008185154_initial.js"

export const migrations = {
  "20261008185154_initial": _20261008185154_initial.default,
} as const
