// Auto-generated by migrate.ts - do not edit
import * as _20261008214414_initial from "./20261008214414_initial.js"

export const migrations = {
  "20261008214414_initial": _20261008214414_initial.default,
} as const
