// Auto-generated by migrate.ts - do not edit
import * as _20261006155914_initial from "./20261006155914_initial.js"

export const migrations = {
  "20261006155914_initial": _20261006155914_initial.default,
} as const
