#!/usr/bin/env npx tsx
import { BunServices, BunRuntime } from "@effect/platform-bun"
import { FileSystem, Path } from "effect"
import { Array as EffectArray, Console, Effect, pipe, Schema, String as EffectString } from "effect"
import { ChildProcess, ChildProcessSpawner } from "effect/unstable/process"

const ATLAS_DIR = "src/db/migrations-sql"
const EFFECT_DIR = "src/db/migrations-effect"
const ATLAS_ENV = "local"

const MigrationNameArg = Schema.String.pipe(
  Schema.check(Schema.isMinLength(1)),
  Schema.check(Schema.isPattern(/^[a-z][a-z0-9_]*$/)),
  Schema.annotate({
    message: "Migration name must be lowercase alphanumeric with underscores",
  }),
)

const escapeForTemplateLiteral = (sql: string): string =>
  sql.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")

const parseSqlStatements = (content: string): Array<string> =>
  content
    .split(";")
    .map((s) => s.trim())
    .filter((s) => s.length > 0)

const generateEffectMigration = (statements: Array<string>, baseName: string): string => {
  const escaped = statements.map(escapeForTemplateLiteral)
  return `// This file was autogenerated by \`migrate.ts\` based on \`src/db/migrations-sql/${baseName}.sql\`
import { SqlClient } from "effect/unstable/sql"
import { Effect } from "effect"

export default Effect.gen(function*() {
  const sql = yield* SqlClient.SqlClient
${escaped.map((stmt) => `  yield* sql\`${stmt}\``).join("\n\n")}
})
`
}

const generateIndexFile = (migrationNames: Array<string>): string => {
  const imports = migrationNames
    .map((name) => {
      const safeName = name.replace(/\W/g, "_")
      return `import * as _${safeName} from "./${name}.js"`
    })
    .join("\n")

  const exports = migrationNames
    .map((name) => {
      const safeName = name.replace(/\W/g, "_")
      return `  "${name}": _${safeName}.default,`
    })
    .join("\n")

  return `// Auto-generated by migrate.ts - do not edit
${imports}

export const migrations = {
${exports}
} as const
`
}

const formatSchemaSQL = Effect.gen(function* () {
  yield* Effect.log("Formatting schema file")

  const spawner = yield* ChildProcessSpawner.ChildProcessSpawner
  const command = ChildProcess.make("sql-formatter", ["--fix", "src/db/schema.sql"], {
    stdout: "inherit",
    stderr: "inherit",
  })

  const result = yield* spawner.exitCode(command)

  if (result !== ChildProcessSpawner.ExitCode(0)) {
    yield* Effect.log("sql-formatter not found or failed, skipping formatting")
  }
})

const runAtlasDiff = (migrationName: string) =>
  Effect.gen(function* () {
    yield* Effect.log(`Running atlas migrate diff: ${migrationName}`)

    const spawner = yield* ChildProcessSpawner.ChildProcessSpawner
    const command = ChildProcess.make(
      "npx",
      ["@ariga/atlas", "migrate", "diff", migrationName, "--env", ATLAS_ENV],
      {
        stdout: "inherit",
        stderr: "inherit",
      },
    )

    const result = yield* spawner.exitCode(command)

    if (result !== ChildProcessSpawner.ExitCode(0)) {
      return yield* Effect.fail(new Error(`Atlas exited with code ${result}`))
    }

    yield* Effect.log("Atlas migration generated successfully")
  })

const convertMigrations = Effect.gen(function* () {
  const fs = yield* FileSystem.FileSystem
  const path = yield* Path.Path

  const atlasPath = path.resolve(ATLAS_DIR)
  const effectPath = path.resolve(EFFECT_DIR)

  yield* fs.makeDirectory(effectPath, { recursive: true })

  const allFiles = yield* fs.readDirectory(atlasPath)
  const sqlFiles = pipe(
    allFiles,
    EffectArray.filter((f) => f.endsWith(".sql")),
    EffectArray.sort(EffectString.Order),
  )

  if (EffectArray.isArrayEmpty(sqlFiles) === true) {
    yield* Effect.log("No SQL migration files found")
    return
  }

  const migrationNames: Array<string> = []

  for (const file of sqlFiles) {
    const content = yield* fs.readFileString(path.join(atlasPath, file))
    const baseName = file.replace(".sql", "")
    const statements = parseSqlStatements(content)

    if (statements.length === 0) {
      yield* Effect.log(`Skipping ${file} (no statements)`)
      continue
    }

    const effectCode = generateEffectMigration(statements, baseName)
    const outputPath = path.join(effectPath, `${baseName}.ts`)

    yield* fs.writeFileString(outputPath, effectCode)
    yield* Effect.log(`${file} -> ${baseName}.ts (${statements.length} statements)`)

    migrationNames.push(baseName)
  }

  const indexContent = generateIndexFile(migrationNames)
  yield* fs.writeFileString(path.join(effectPath, "index.ts"), indexContent)
  yield* Effect.log(`Generated index.ts with ${migrationNames.length} migrations`)
})

const program = Effect.gen(function* () {
  const args = yield* Effect.sync(() => process.argv.slice(2))

  if (args.length === 0) {
    yield* Console.error("Usage: npx tsx scripts/migrate.ts <migration_name>")
    yield* Console.error("Example: npx tsx scripts/migrate.ts add_users_table")
    return yield* Effect.fail(new Error("Missing migration name"))
  }

  const migrationName = yield* Schema.decodeUnknownEffect(MigrationNameArg)(args[0]).pipe(
    Effect.mapError(
      () => new Error("Invalid migration name. Use lowercase alphanumeric with underscores."),
    ),
  )

  yield* formatSchemaSQL
  yield* runAtlasDiff(migrationName)
  yield* convertMigrations

  yield* Effect.log("\nMigration complete!")
})

pipe(program, Effect.provide(BunServices.layer), BunRuntime.runMain)
